### ISSUE TITLE
how to add menus?

### ISSUE THREAD

**Issue by ghost** [LukasJoswiak/etch#5]
I might be missing something (I'm not a developer), but the default method to insert methods I'm used to from other themes doesn't seem to be working. I'm following the instructions from [the documentation](https://gohugo.io/content-management/menus/#add-content-to-menus), for example

```toml
[menu]

  [[menu.main]]
    identifier = "page"
    name = "my page title"
    url = "/mypage/"
    weight = 1
```

Doesn't result in a menu. Is there another way to create menu items for the navigation bar? 

Cheers!
