### ISSUE TITLE
Question: how to set the post creation dates visible?

### ISSUE THREAD

**Issue by padaszewski** [LukasJoswiak/etch#55]
Hi,
In Your example You have visible dates on the posts
![image](https://user-images.githubusercontent.com/30108423/218708795-dce7e34c-7d6d-4a29-92e4-793f54eb3b60.png)

In my case these dates does not appear:
![image](https://user-images.githubusercontent.com/30108423/218708916-d2e84a6b-7d69-4082-9c83-1395c55382b3.png)

I have the same config as in the example site.
Is there a specific param to set in order to get this work?

**Comment by LukasJoswiak** [comment]
You need to set the `date` param in the [front matter](https://gohugo.io/content-management/front-matter/) for the post.

**Comment by padaszewski** [comment]
Sure, I've done that. I even copied the front matter from the example and got the same result:
```
+++
author = "Hugo Authors"
title = "Test"
date = 2019-03-05
description = "Guide to emoji usage in Hugo"
tags = [
"emoji",
]
+++
```
![image](https://user-images.githubusercontent.com/30108423/218981433-c218a8e7-73a1-479e-834b-a9363f4e46ca.png)

Before that I had a simple json with `title`, `date` and `draft`

**Comment by LukasJoswiak** [comment]
What version of Hugo are you running?

```
$ hugo version
hugo v0.104.3+extended darwin/amd64 BuildDate=unknown
```

**Comment by LukasJoswiak** [comment]
There shouldn't be any specific parameter to enable to display the dates, they should just show by default.

**Comment by LukasJoswiak** [comment]
If you click through to the page for the post, does it show the date under the title, like it does at https://lukasjoswiak.github.io/etch/markdown-syntax-guide/?

**Comment by younsl** [comment]
@padaszewski

Here's my codes I am using.

## Environment

### Content

Set `data` and `lastmod` on each post.

```yaml
---
title: "도커 파일시스템 정리"
date: 2022-03-16T13:07:20+09:00
lastmod: 2022-08-31T10:03:10+09:00
slug: ""
description: "쿠버네티스 워커 노드가 파일시스템 사용률이 높을 때, docker system prune 명령어를 실행해서 Docker 오브젝트를 정리하여 파일시스템 공간을 확보할 수 있다."
keywords: []
tags: ["os", "linux", "docker"]
---

... then contents from now on ...
```

### Config

```toml
baseURL                = "https://younsl.github.io"
title                  = "younsl"
theme                  = "etch"
languageCode           = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences     = true
pygmentsUseClasses     = true
disableKinds           = ["taxonomy", "term"]

[params]
  description = "younsl"
  copyright   = ""
  dark        = "on"
  highlight   = true

[article]
  showComments      = true
  showAdvertisement = true

[menu]
  [[menu.main]]
    identifier = "wiki"
    name       = "wiki"
    title      = "wiki"
    url        = "/wiki/"
    weight     = 10

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true

```

&nbsp;

## Output

Here's what the webpage looks like in the Chrome browser.

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/87736192/219845030-96e08208-56e5-48fa-9734-b1f861b3e586.png">

<img width="712" alt="image" src="https://user-images.githubusercontent.com/87736192/219845112-09ca869b-8da7-4841-a627-4f0ad1da7cc3.png">

&nbsp;

- In my case, `date` and `lastmod` frontmatter are output normally without any specific `config.toml` settings.
- You need to set `date` and `lastmod` value in the post frontmatter.
